name: 'Terraform GitHub Actions'
on:
  push:
    branches:
      - main

jobs:
  validate-step:
    name: 'Validation Step'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.9
          tf_actions_subcommand: "init"
        env:
          GITHUB_TOKEN: ${{secrets.PA_TOKEN}}
      - name: 'Terraform Validate'
        run: terraform validate
      - name: 'Terraform Plan'
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: terraform plan
  deploy-step:
    name: 'Deployment Step'
    runs-on: ubuntu-latest
    environment: 'TomsAWS-QA'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.9
          tf_actions_subcommand: "init"
        env:
          GITHUB_TOKEN: ${{secrets.PA_TOKEN}}
      - name: 'Terraform Validate'
        run: terraform validate
      - name: 'Terraform Apply'
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: terraform plan
  complete-step:
    name: 'Complete or Rollback?'
    runs-on: ubuntu-latest
    environment: 'TomsAWS-QA-Rollback'
    needs: deploy-step
    steps:
      - name: 'Say hi'
        run: echo "Hello World"

      


